// examples/react18/src/main.tsx
import ReactDOM from 'react-dom/client'
import { StrictMode } from 'react'

import { Button, Modal } from 'antd'

import {
  imperativeRender,
  asyncImperativeRender,
  ImperativeRenderProps,
} from '../node_modules/imperative-render/src/react'

type Props = ImperativeRenderProps & {
  title: string
}
const YourComponent = ({ controller, title }: Props) => {
  return (
    <Modal
      title={`${controller.index}. ${title}`}
      open={controller.active}
      onOk={() => {
        controller.resolve('fire onOk')
      }}
      onCancel={() => {
        controller.reject('fire onCancel')
      }}
      // afterClose={controller.destroy}
    >
      无敌的凯之巨人
      <Button
        onClick={async () => {
          const r = await controller.waitUntil(
            asyncImperativeRender(YourComponent, { title: 'asyncImperativeRender modal' }),
          )
          console.log('r', r)
        }}
      >
        自由
      </Button>
    </Modal>
  )
}

function App() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '70vh' }}>
      <Button
        onClick={() => {
          const instance = imperativeRender(YourComponent, { title: 'imperativeRender modal' })
          console.log('imperativeRender', instance)
          instance.promise.then(console.info).catch(console.warn)
        }}
      >
        imperativeRender modal
      </Button>
      <Button
        onClick={async () => {
          const value = await asyncImperativeRender(YourComponent, { title: 'asyncImperativeRender modal' })
          console.info('imperativeRender', value)
        }}
      >
        asyncImperativeRender modal
      </Button>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

// examples/vue3/src/main.tsx
import { createApp, defineComponent } from 'vue'

import { imperativeRender, asyncImperativeRender } from '../node_modules/imperative-render/src/vue'
import type { ImperativeRenderController } from '../node_modules/imperative-render/src/vue'
import { NButton, NCard, NModal } from 'naive-ui'

const YourComponent = defineComponent({
  props: {
    controller: Object as () => ImperativeRenderController,
    title: String,
  },
  setup(props) {
    const controller = props.controller!
    console.log('controller', controller)

    return () => {
      return (
        <NModal show={controller.active.value}>
          <NCard title={`${controller.index}. ${props.title}`} style={{ width: '50vw' }}>
            <p>无敌的凯之巨人</p>
            <NButton
              onClick={() => {
                controller.waitUntil(asyncImperativeRender(YourComponent, { title: '套中套' })).then(console.info)
              }}
            >
              再开一个
            </NButton>
            <NButton onClick={() => controller.resolve('fire onCancel')}>resolve</NButton>
            <NButton onClick={() => controller.reject('fire onCancel')}>reject</NButton>
          </NCard>
        </NModal>
      )
    }
  },
})

const App = defineComponent({
  setup(props) {
    return () => {
      return (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '70vh' }}>
          <NButton
            secondary
            onClick={() => {
              imperativeRender(YourComponent, { title: '神罗天征' })
            }}
          >
            神罗天征
          </NButton>
        </div>
      )
    }
  },
})

createApp(App).mount('#app')
